src.dir=src/main/java
web.dir=src/main/webapp
test.dir=src/test/java
lib.dir=lib

ant.build.dir=build-ant
classes.dir=${ant.build.dir}/classes
test.classes.dir=${ant.build.dir}/test-classes
report.dir=${ant.build.dir}/reports
dist.dir=dist

project.name=Lab3-JSF
version=1.0.0
main.class=lab.Main
jar.name=${project.name}-${version}.jar

scp.host=se.ifmo.ru
scp.port=2222
scp.user=s467141
scp.password=joVW{9624
scp.dir=./opi_lab3/

music.dir=ant/sound
music.success=success.wav
music.fail=fail.wav

diff.classes=AreaBean.java
git.commit.message=Auto-commit from Ant diff target: AreaBean changed

svn.repo.url=file:///Users/voisik/svn_for_opi/local-svn-repo
team.temp.dir=${ant.build.dir}/team-temp
team.zip.name=${dist.dir}/revisions.zip

alt.src.dir=${ant.build.dir}/alt-src
alt.regex.match=r10
alt.regex.replace=radius10
alt.jar.name=${project.name}-ALT-${version}.jar


mail.smtp.host=smtp.yandex.ru
mail.smtp.port=465
mail.smtp.user=voisiklol@yandex.ru
mail.smtp.password=ekdnmqeguwrgfart
mail.smtp.ssl=true