<?xml version="1.0" encoding="UTF-8"?>
<ivy-module version="2.0">
    <info organisation="lab" module="web-prog-lab3"/>

    <dependencies>
        <dependency org="javax" name="javaee-api" rev="8.0.1" conf="default->default"/>
        <dependency org="org.primefaces" name="primefaces" rev="13.0.0" conf="default->default"/>
        <dependency org="org.postgresql" name="postgresql" rev="42.7.8" conf="default->default"/>

        <dependency org="junit" name="junit" rev="4.13.2" conf="default->default"/>
        <dependency org="com.jcraft" name="jsch" rev="0.1.55" conf="default->default"/>

        <dependency org="org.jacoco" name="org.jacoco.ant" rev="0.8.11" conf="default->default"/>

        <dependency org="com.sun.mail" name="javax.mail" rev="1.6.2" conf="default->default"/>
        <dependency org="javax.activation" name="activation" rev="1.1.1" conf="default->default"/>
    </dependencies>
</ivy-module>